---
- hosts: jenkins-master
  become: true
  tasks:
  - name: add jenkins key
    apt_key:
      url: 
      state: present
  
  - name: add jenkins repo
    apt_repository:
      repo: ''
      state: present

  - name: Install java
    apt:  
      name: openjdk-11-jre
      state: present

  - name: install jenkins
    apt:
      name: jenkins
      state: present

  - name: start jenkins server
    service:
      name: jenkins
      state: started

  - name: enable jenkins to start at boot
    service:
      name: jenkins
      enabled: yes